import { PricingPlan } from "@/types";

export const PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    plan: "free",
    credits: 10,
    monthlyPrice: 0,
    annualPrice: 0,
    features: [
      "10 free credits",
      "Standard quality",
      "PNG & JPG export",
      "Basic backgrounds",
      "Community support",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    plan: "starter",
    credits: 500,
    monthlyPrice: 9,
    annualPrice: 90,
    features: [
      "500 credits/month",
      "HD quality",
      "All export formats",
      "Custom backgrounds",
      "API access",
      "Email support",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    plan: "pro",
    credits: 5000,
    monthlyPrice: 29,
    annualPrice: 290,
    popular: true,
    features: [
      "5,000 credits/month",
      "Ultra HD quality",
      "All export formats",
      "Custom & AI backgrounds",
      "Batch processing",
      "Priority API access",
      "Priority support",
    ],
  },
  {
    id: "business",
    name: "Business",
    plan: "business",
    credits: "unlimited",
    monthlyPrice: 99,
    annualPrice: 990,
    features: [
      "Unlimited credits",
      "Ultra HD quality",
      "All export formats",
      "Custom & AI backgrounds",
      "Batch processing",
      "Full API access",
      "Team workspace",
      "Dedicated support",
      "Custom integrations",
    ],
  },
];
